# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('tu', 'Tutorial'), ('fx', 'Fix')], default='tu', max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['post_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.IntegerField(blank=True, default=0)),
                ('pic', models.URLField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('forpost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserve.post')),
            ],
            options={
                'ordering': ['forpost', 'steps'],
            },
        ),
    ]
